# API Gateway - RestauranteTech
# Todo el trafico externo entra unicamente por aqui (puerto 8080).
# Los microservicios NO se exponen directamente al cliente.

events {
    worker_connections 1024;
}

http {
    upstream menu-service {
        server svc-menu:8081;      # nombre del servicio en la red Docker
    }
    upstream orders-service {
        server svc-orders:8082;    # nombre del servicio en la red Docker
    }
    upstream inventory-service {
        server svc-inventory:8083; # nombre del servicio en la red Docker (punto extra)
    }

    server {
        listen 8080;

        location /api/menu/ {
            proxy_pass http://menu-service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/orders {
            proxy_pass http://orders-service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/inventory/ {
            proxy_pass http://inventory-service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /health {
            return 200 '{"status":"UP","service":"api-gateway"}';
            add_header Content-Type application/json;
        }
    }
}
